version: "3.3"
services:
  sports:
    container_name: sports
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8000:8080"

    volumes:
      - "./src/:/app"
